apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps-manager
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      recurse: true
    path: argocd-config/
    repoURL: https://github.com/JulienJourdain/argocd-playground.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
